# -----------------------------------------------------------------------------
# Install Trivy
#
# Description:
#   This GitHub Action installs the Trivy Software Composition Analysis (SCA) tool
#   on the runner environment. Trivy is a comprehensive vulnerability scanner that 
#   is used to detect security issues in container images, file systems, and 
#   software dependencies.
#
# Usage Example:
#   jobs:
#     sca:
#       runs-on: ubuntu-latest
#       steps:
#         - name: Checkout code
#           uses: actions/checkout@v4
#
#         - name: Install Trivy
#           uses: 2Toad/actions/install-trivy@v1
#   
#         - name: Run Trivy SCA Scan
#           uses: 2Toad/actions/run-trivy@v1
#           with:
#             path: "./src"
#             severity: "MEDIUM,HIGH,CRITICAL"
#
# -----------------------------------------------------------------------------

name: "Install Trivy"
description: "Install Trivy SCA tool"
runs:
  using: "composite"
  steps:
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y
